### ISSUE TITLE
Checkbox handlers report id of element

### ISSUE THREAD

**Issue by natestormer** [synapsestudios/synfrastructure#48]
Checkboxes should respond with `this.props.id, this.props.checked, event` like the Radio components

**Comment by spruce-bruce** [comment]
checkbox already responds with this.props.id, that's the problem right?

**Comment by spruce-bruce** [comment]
also it might be worth reconsidering the value of even having a checkbox component. Right now it wraps event handlers and I think adds a className? I'm not sure we're getting anything valuable out of this.
