### ISSUE TITLE
Fix validation message schema

### ISSUE THREAD

**Issue by spruce-bruce** [synapsestudios/synfrastructure#51]
I think the validation component should be updated to take an `errors` prop instead of a `validation` prop. Errors will either be a string or an array of strings. It will be assumed that if errors is set then we have errors to render.

Currently we do `validation = {{status: 'error', messages: ['a message']}}`. Messages is forced to be an array, which is too rigid, and I've never seen us use any status other than 'error'. If there are other statuses used elsewhere we should update the api to take a separate prop for those messages.

So,
1. Get rid of validation prop
2. add errors prop that can be a string or an array of strings
3. Maybe add a 'success' or 'messages' prop for other messages? I don't know where we use this functionality now so maybe we don't do this.

**Comment by nearengine** [comment]
+1

**Comment by tdboone** [comment]
:+1:

**Comment by kylecesmat** [comment]
+2

**Comment by spruce-bruce** [comment]
Talked to designers, they use other statuses like success and warning. They do this for things like positive validation (think passwords, like 'yes your password is strong!' or "we'll allow this password, but it's not that strong")

The current plan is modified to,
1. Get rid of validation prop
2. add errors prop that can be a string or an array of strings
3. add successMessages prop that can be a string or an array of strings
4. add warnings prop that can be a string or an array of strings

**Comment by spruce-bruce** [comment]
:hand:

**Comment by spruce-bruce** [comment]
merged!
