### ISSUE TITLE
Label.type throws Uncaught TypeError

### ISSUE THREAD

**Issue by chrisheninger** [synapsestudios/synfrastructure#78]
When using a <Label> tag with children but no label (this happens with our scaffolding components occasionally) the function in the constructor checking the children types for `Checkbox/Radio` receives `null` and throws the following: `Uncaught TypeError: Cannot read property 'type' of null`

I can fix this– just wanted to throw an issue in here so I remembered.

**Comment by chrisshiplet** [comment]
Same 🤷‍♂️
